### ISSUE TITLE
link to depreciated tool

### ISSUE THREAD

**Issue by perezjasonr** [JAORMX/selinux-policy-helper-operator#2]
Note that this now requires the selinux-operator to be installed:

https://github.com/JAORMX/selinux-operator

but that link says

`The work has now moved towards the Security Profiles Operator which now hosts the functionality that the selinux-operator initially introduced.`

so is this a total disconnect from this tool? or does it now work with "Security Profiles Operator"

**Comment by JAORMX** [comment]
@perezjasonr we'll add this functionality to the Security Profiles Operator too.

**Comment by perezjasonr** [comment]
thank you for the clarification, so if I'm understanding this right. this tool (selinux-policy-helper-operator) and (selinux-k8s) are all going over to security profiles operator? so is selinux-policy-helper-operator also in a way depreciated and its efforts will all be wrapped up in security profiles operator?

so it wont be install security profiles operator, and this tool will work with that as a prereq, it will all be security profiles operator?

**Comment by JAORMX** [comment]
> thank you for the clarification, so if I'm understanding this right. this tool (selinux-policy-helper-operator) and (selinux-k8s) are all going over to security profiles operator? so is selinux-policy-helper-operator also in a way depreciated and its efforts will all be wrapped up in security profiles operator?
> 
> so it wont be install security profiles operator, and this tool will work with that as a prereq, it will all be security profiles operator?

That's correct.  This project is no longer maintained and the functionality will exist in the Security Profiles Operator

**Comment by perezjasonr** [comment]
aight thank you. closing.
